#!/bin/bash
#
# Copyright (c) 2011 Nokia Corporation.
# Author: Lauri T. Aarnio
#
# Licensed under LGPL version 2.1, see top level LICENSE file for details.

# Emulate "fakeroot" for SB2.
# SB2 does not use fakeroot anymore, if has built-in functionality
# for the same things in libsb2.

export SBOX_VPERM_REQUEST="u0:0:0:0,g0:0:0:0"
if [ $# -gt 0 ]; then
	exec $SHELL -c "$@"
else
	exec $SHELL
fi
