#!/bin/bash
#
# Wrapper for host-* tools. This is not used, if use of the host-*
# tools are allowed! in that case the preload library will modify
# exec so that the real tool is executed, and not this one.
#
# Copyright (c) 2008 Nokia Corporation.
# All rights reserved.
# Author: Lauri T. Aarnio
#
# Licensed under GPL version 2

progbase=`basename $0`

echo "SB2: $progbase wrapper: Operation denied."
echo "SB2: $progbase wrapper: You see this message because the real $progbase tool"
echo "SB2: $progbase wrapper: is not available in this environment / mapping mode"

# FIXME: host-* used to be links to /bin/true; return true for compatibility,
# but we probably should do "exit 0" here...
exit 0

