#!/bin/sh
# Copyright (C) 2007 Lauri Leukkunen <lle@rahina.org>
# Licensed under GPL version 2

args=$(echo "$*" | sed 's/[[:space:]]\+-f[[:space:]]\+/ /g' | sed 's/^-f$//' | sed 's/^-f[[:space:]]\+//' | sed 's/-f$//')
/usr/bin/dpkg-architecture $args

