#!/bin/bash
# sb2-build-libtool - Copyright (C) 2007 Lauri Leukkunen <lle@rahina.org>
# Licensed under GPL version 2

# test that we're inside sb2
if [ -z "$SBOX_TARGET_ROOT" ]; then
	echo "Please run this script inside sb2, like this:
$ sb2 $0"
	exit 1
fi

set -e

NAME=libtool
VERSION=1.5.22

DLHOST="http://ftp.funet.fi/pub/mirrors/ftp.gnu.org/pub/gnu/libtool"
SOURCEFILE=$NAME-$VERSION.tar.gz
COMPILERDIR=
WORKDIR=$(mktemp -d -t sb2_libtool_build.XXXXXXX) || exit 1
cd $WORKDIR

if [ ! -e ../$SOURCEFILE ]; then
	wget $DLHOST/$SOURCEFILE -O ../$SOURCEFILE
fi

tar zxf ../$SOURCEFILE --strip-components=1


./configure --prefix=$SBOX_TARGET_ROOT/sb_tools --build=$(uname -m)-unknown-linux-gnu

# The system libtool script in Debian must be able to support
# invoking gcc as cc (Debian specific)
echo '# ### BEGIN LIBTOOL TAG CONFIG: BINCC' >> libtool
sed -n -e '/^# ### BEGIN LIBTOOL CONFIG/,/^# ### END LIBTOOL CONFIG/p' < libtool \
	| grep -B 2 -A 1 -e '^LTCC=' -e '^CC=' \
	| sed -e 's/gcc/cc/g' >> libtool
echo '# ### END LIBTOOL TAG CONFIG: BINCC' >> libtool
echo >> libtool

# The system libtool script in Debian must be able to support
# invoking g++ both by the g++ and c++ names. (Debian specific)
sed -n -e '/^# ### BEGIN LIBTOOL TAG CONFIG: CXX$$/,/^# ### END LIBTOOL TAG CONFIG: CXX$$/p' < libtool \
	| sed -e 's/CONFIG: CXX/CONFIG: BINCXX/g' \
		-e 's/g++/c++/g' >> libtool
echo >> libtool

# Add our BINCC and BINCXX tags (Debian specific)
sed -e 's/^\(available_tags\)=\"\(.*\)\"/\1=\"\2 BINCC BINCXX\"/' \
	< libtool > libtool.tags
mv libtool.tags libtool

# Make libtool executable again
chmod 755 libtool


make
# create these directories to work around ppc host issues
mkdir -p $SBOX_TARGET_ROOT/sb_tools/share/aclocal
mkdir -p $SBOX_TARGET_ROOT/sb_tools/share/libtool/libltdl
mkdir -p $SBOX_TARGET_ROOT/sb_tools/lib
mkdir -p $SBOX_TARGET_ROOT/sb_tools/include
make install
cd ..
# cleanup
rm -rf $WORKDIR

