#!/scratchbox/bin/bash-static

FAKECHROOT=true
FAKECHROOT_VERSION=2.5
FAKECHROOT_BASE=/scratchbox
export FAKECHROOT FAKECHROOT_VERSION

REDIR_LD_LIBRARY_PATH="/scratchbox/lib:/scratchbox/usr/lib:/scratchbox/usr/X11R6/lib"
LD_PRELOAD="/scratchbox/fakechroot/libsb2.so"
SBOX_REDIR_SCRIPTS="/scratchbox/redir_scripts"
REDIR_LD_SO=$FAKECHROOT_BASE/lib/ld-linux.so.2
export LD_PRELOAD REDIR_LD_LIBRARY_PATH REDIR_LD_SO

exec $REDIR_LD_SO --library-path $REDIR_LD_LIBRARY_PATH $FAKECHROOT_BASE/bin/bash

exit 1
