#!/bin/sh -x

scriptdir=`dirname $0`
SBOXDIRNAME=scratchbox

#FIXME setting up cputransparency

if [ x$3 == x ]
then
	echo "Usage: $0 target compiler <debootstrap options>"
	exit
fi

#ugly

target=$1
shift
compiler=$1
shift
suite=$1
shift
debootstrap_opts="$suite $target/scratchbox/ $@"


if [ -e $target ]
then
	echo "Cowardly refusing to devastate existing $sbox2target"
	exit 1
fi

if [ `id -u` != 0  ]
then
	echo "Need to be root"
	exit 2
fi

# FIRE!

mkdir -p $target/scratchbox/fakechroot

debootstrap $debootstrap_opts

# FIXME install build-essential, qemu, etc, $target/scratchbox/
chroot $target/scratchbox/ apt-get update
chroot $target/scratchbox/ apt-get install -y bash-static make patch perl dpkg-dev perl-modules liblua5.1-0
chroot $target/scratchbox/ apt-get clean

cp /usr/lib/scratchbox2/fakechroot/* $target/scratchbox/fakechroot/
cp /usr/lib/scratchbox2/redir_scripts $target/scratchbox/
