#!/bin/sh 

is_sane_sbox2()
{
	target=$1
	
	if [ ! -d $target ] 
	then
		echo "Not a directory: $target"
		return 1
	fi

	if [ ! -d $target/$SBOXDIRNAME ]
	then
		echo "$target does not look like a scratchbox2 target"
		return 1
	fi
	
	if [ ! -x $target/$SBOXDIRNAME/fakechroot/fakechroot ]
	then
		echo "$target does not contain scratchbox2 support scripts"
		return 1
	fi

	if [ ! -x $target/$SBOXDIRNAME/bin/bash-static ] 
	then
		echo "$target/$SBOXDIRNAME/bin/bash-static does not exist!"
		return 2
	fi

	return 0
}

sbox2target=$1
scriptdir=`dirname $0`
SBOXDIRNAME=scratchbox

if is_sane_sbox2 $1
then
	/usr/bin/chroot-uid $sbox2target /$SBOXDIRNAME/fakechroot/fakechroot
fi
