#!/bin/sh -x

SBOXDIRNAME=scratchbox

#FIXME setting up cputransparency

if [ x$2 == x ]
then
	echo "Unpacks a previously recorded sbox hostkit"
	echo "Usage: $0 /store/hostkit.tgz directory-to-unpack-to"
	exit
fi

echo -n "Unpacking host tarball.."
tar xzf $1 -C $2 $SBOXDIRNAME && echo " Done!" || " Failed!"
