#!/bin/sh -x

SBOXDIRNAME=scratchbox

#FIXME setting up cputransparency

if [ x$2 == x ]
then
	echo "Usage: $0 /store/hostkit.tgz scratchbox-system"
	exit
fi

echo "Creating host tarball"
tar cvzf $1 -C $2 $SBOXDIRNAME

# FIRE!


