.TH sb2-config 1 "17 December 2010" "2.2" "sb2-config man page"
.SH NAME
sb2-config \- scratchbox2 configuration tool
.SH SYNOPSIS
.B sb2-config [OPTION]... [COMMAND [PARAMS]]

.SH DESCRIPTION
.B sb2-config
is used to set and display configuration of existing targets.

.SH OPTIONS
.TP
\-d default_target
This option sets the default sb2 target. The name of the target will be written to your $HOME/.scratchbox2/config file.
.TP
\-l
lists all available targets in your system. The names listed can be used as a parameter to the -d option.
.TP
\-h
Display short help.
.TP
\-v
Show version of this tool.
.TP
\-t target
select target to be used with commands (below)

.SH COMMANDS
.TP
showtarget
show default target.
.TP
showlog
show configuration log
.TP
showenv
show target-specific environment variables
.TP
setenv VARIABLE VALUE
set target-specific environment variable. The value becomes effective when
.I sb2
is executed.
.TP
clearenv VARIABLE
set clearing for target-specific environment variable
.TP
unsetenv VARIABLE
remove target-specific environment variable

.SH EXAMPLES

.nf
$ sb2-config -d diablo41_armel

This command sets your default target to be diablo41_armel.

$ sb2-config -l

This example lists all installed targets in your host. The names listed can be used as a parameter to the -d option.

.fi


.SH SEE ALSO
.BR sb2 (1),
.BR sb2-init (1),
.BR sb2-show (1)

.SH AUTHOR
.nf
Lauri Leukkunen
.fi
