Import("env")

fuse_env = env.Copy()

fuse_env.Append(CXXFLAGS = ["-D_XOPEN_SOURCE=500",
	"-D_LARGEFILE_SOURCE", "-D_FILE_OFFSET_BITS=64"])

sb2fs_env = fuse_env.Copy()

fuse_env.SharedLibrary("sb2fuse", ["common/fuse.cpp"])
fuse_env.Library("sb2fuse", ["common/fuse.cpp"])


sb2fs_env.Append(LIBPATH = ["../lua", "."])

sb2fsindep = sb2fs_env.Copy()
sb2fs_env.Append(LIBS = ["sb2fuse", "lua_bindings", "fuse"])
sb2fs_env.Program("sb2fs", ["miscfs/sb2fs.o"])

sb2fsindep.Append(LIBS = ["lua_bindings", "fuse"], _LIBFLAGS=" fuse/libsb2fuse.a")
sb2fsindep.Program("sb2fs-indep", ["miscfs/sb2fs.cpp"])


